import csv

# Datos extraídos del texto proporcionado
data = [
    ["Carlos", "Fossati", "25-06-1919", "", "", "", "", ""],
    ["María Teresa", "Peruzzo", "08-04-1926", "", "", "", "", ""],
    ["Edgardo Rubén", "Fossati", "27-01-1952", "", "", "", "", ""],
    ["Silvia Mónica", "Urseler", "19-07-1960", "", "", "", "", ""],
    ["Eliana Yamile", "Fossati", "01-03-1990", "", "", "", "", ""],
    ["Shirley Evelin", "Fossati", "20-09-1992", "", "", "", "", ""],
    ["Jeremías Rubén", "Fossati", "20-09-1992", "", "", "", "", ""],
    ["Nanci Élida", "Fossati", "29-04-1955", "", "", "", "", ""],
    ["Arturo Joaquín", "Sargiotto", "26-12-1956", "", "", "", "", ""],
    ["María Daniela", "Sargiotto", "16-04-1983", "", "", "", "", ""],
    ["Andrés Elio", "Sargiotto", "27-05-1985", "", "", "", "", ""],
    ["Yasmín", "Dalmau", "10-07-1990", "", "", "", "", ""],
    ["Carmela", "Sargiotto", "27-11-2023", "", "", "", "", ""],
    ["Augusto Julián", "Sargiotto", "25-08-1992", "", "", "", "", ""],
    ["Alfonso Emmanuel", "Sargiotto", "27-07-1994", "", "", "", "", ""],
    ["Melina Beatriz", "Cena", "09-10-1997", "", "", "", "", ""],
    ["Néstor Carlos", "Fossati", "12-10-1957", "", "", "", "", ""],
    ["María Alejandra", "Corti", "22-01-1965", "", "", "", "", ""],
    ["Álvaro Luis", "Fossati", "14-11-1992", "", "", "", "", ""],
    ["Octavio Nahuel", "Fossati", "02-04-1999", "", "", "", "", ""],
    ["Marisa Nelly", "Fossati", "15-09-1969", "", "", "", "", ""],
    ["Ricardo Hernán", "Bosio", "27-01-1963", "", "", "", "", ""],
    ["Rocío", "Bosio", "13-05-1995", "", "", "", "", ""],
    ["Martina", "Bosio", "19-09-2001", "", "", "", "", ""],
    ["Alberto", "Fossati", "1921", "", "", "23-05-1991", "", ""],
    ["Beatriz", "Peruzzo", "", "", "", "", "", ""],
    ["Marta Mabel", "Fossati", "1959", "", "", "31-08-1969", "", ""],
    ["Beatriz Teresa Dominga", "Fossati", "", "", "", "", "", ""],
    ["Ismael", "Lizarazo", "", "", "", "", "", ""],
    ["Agustín", "", "", "", "", "", "", ""],
    ["Anahí", "", "", "", "", "", "", ""],
    ["Santiago", "Demo", "", "", "", "", "", ""],
    ["Florencia", "González", "", "", "", "", "", ""],
    ["Norma", "", "", "", "", "", "", ""],
    ["Daniel", "Chiaraviglio", "", "", "", "", "", ""],
    ["Emmanuel", "", "", "", "", "", "", ""],
    ["Adelina", "Fossati", "", "", "", "", "", ""],
    ["Tomás Bendito", "Marchio", "", "", "", "", "", ""],
    ["Héctor Tomás", "Marchio", "", "", "", "", "", ""],
    ["Lucero", "", "", "", "", "", "", ""],
    ["Natalia", "", "", "", "", "", "", ""],
    ["Jorge", "Jaime", "", "", "", "", "", ""],
    ["Gabriel", "Jaime", "", "", "", "", "", ""],
    ["Luis", "Rosso", "", "", "", "", "", ""],
    ["Miranda", "Rosso", "", "", "", "", "", ""],
    ["Ricardo", "", "", "", "", "", "", ""],
    ["Jorge", "", "", "", "", "", "", ""],
    ["Mónica", "González", "", "", "", "", "", ""],
    ["Karina", "", "", "", "", "", "", ""],
    ["Santiago", "Cuchietti", "", "", "", "", "", ""],
    ["Benicio", "", "", "", "", "", "", ""],
    ["Luisina", "", "", "", "", "", "", ""],
    ["Daniela", "", "", "", "", "", "", ""],
    ["Delfina", "Fossati", "", "", "", "", "", ""],
    ["Juan Bautista", "", "", "", "", "", "", ""],
    ["Alicia", "", "", "", "", "", "", ""],
    ["Mattos", "", "", "", "", "", "", ""],
    ["Bruno", "Mattos", "", "", "", "", "", ""],
    ["Fabián", "", "", "", "", "", "", ""],
    ["María de los Ángeles", "Rosso", "", "", "", "", "", ""],
    ["Ana Paula", "", "", "", "", "", "", ""],
    ["Marco", "", "", "", "", "", "", ""],
    ["Héctor", "Fossati", "", "", "", "", "", ""],
    ["Sofía", "", "", "", "", "", "", ""],
    ["Clide", "", "", "", "", "", "", ""],
    ["Gassmann", "", "", "", "", "", "", ""],
    ["Gabriel", "", "", "", "", "", "", ""],
    ["Marcelo", "", "", "", "", "", "", ""],
    ["Gabriela", "", "", "", "", "", "", ""],
    ["Muelas", "", "", "", "", "", "", ""],
    ["Juan Manuel", "", "", "", "", "", "", ""],
    ["Lorenzo", "", "", "", "", "", "", ""],
    ["Paulina", "", "", "", "", "", "", ""],
    ["Mariano", "", "", "", "", "", "", ""],
    ["Agostina", "Corti", "", "", "", "", "", ""],
    ["Germán", "", "", "", "", "", "", ""],
    ["Silvia", "Farías", "", "", "", "", "", ""],
    ["Sabrina", "", "", "", "", "", "", ""],
    ["Fabrizio", "", "", "", "", "", "", ""],
    ["Adriana", "", "", "", "", "", "", ""],
    ["Gassmann", "", "", "", "", "", "", ""],
    ["Jonatan", "", "", "", "", "", "", ""],
    ["Roger", "", "", "", "", "", "", ""],
    ["Yael", "Tonelli", "", "", "", "", "", ""],
    ["Blas", "", "", "", "", "", "", ""],
    ["Alex", "", "", "", "", "", "", ""],
    ["Janet", "", "", "", "", "", "", ""],
    ["Gustavo", "", "", "", "", "", "", ""],
    ["Fossati", "Edgardo Rubén", "27-01-1952", "", "", "", "", ""],
    ["Fossati", "Carlos", "25-05-1919", "", "", "12-12-2003", "", ""],
    ["Fossati", "Carlo", "1878", "", "", "", "", ""],
    ["Fossati", "Pedro (Pietro)", "", "", "", "", "", ""],
    ["Bertola", "Juana", "", "", "", "", "", ""],
    ["Daniele", "Dominga", "1888", "", "", "05-10-1940", "", ""],
    ["Daniele", "Pietro", "1859", "", "", "29-05-1912", "", ""],
    ["Antonio", "Daniele", "", "", "", "", "", ""],
    ["Domenica", "Rossi Tarditi", "", "", "", "", "", ""],
    ["Bongiovanni", "Domenica", "", "", "", "", "", ""],
    ["Peruzzo", "María Teresa", "08-04-1928", "", "", "29-12-2002", "", ""],
    ["Peruzzo", "Luis", "1897", "", "", "01-08-1979", "", ""],
    ["Peruzzo", "Amadeo", "", "", "", "", "", ""],
    ["Peressín", "Teresa", "", "", "", "", "", ""],
    ["Giordano", "Remo Teresa (Rémola)", "1908", "", "", "07-02-1993", "", ""],
    ["Giordano", "Carlos", "", "", "", "", "", ""],
    ["Lombardi", "María", "", "", "", "", "", ""],
]

# Especificar el nombre del archivo CSV
# csv_file_path = "/mnt/data/arbol_genealogico_completo.csv"

# Crear el archivo CSV y escribir los datos
with open('family_tree.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data)
